name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest -v

      - name: Build Docker image
        run: docker build -t cute-login-ci .

      # Ejemplo (comentado) de paso de deploy:
      # - name: Deploy (placeholder)
      #   run: |
      #     echo "Aquí iría el comando de deploy a tu plataforma (Railway/Fly/Render/etc.)"
